import { useState } from 'react'
import './BlueprintPreview.css'

function BlueprintPreview({ blueprint, catalogEntry, modelUsed, onSimulate, onBack, simulating, discovery }) {
    const [activeTab, setActiveTab] = useState('blueprint')
    const [editableBlueprint, setEditableBlueprint] = useState(
        JSON.stringify(blueprint, null, 2)
    )
    const [editableCatalog, setEditableCatalog] = useState(
        JSON.stringify(catalogEntry, null, 2)
    )
    const [jsonError, setJsonError] = useState(null)

    const handleSimulate = () => {
        try {
            const parsedBlueprint = JSON.parse(editableBlueprint)
            const parsedCatalog = JSON.parse(editableCatalog)
            setJsonError(null)
            onSimulate(parsedBlueprint, parsedCatalog)
        } catch (e) {
            setJsonError(`Invalid JSON in ${activeTab}: ${e.message}`)
        }
    }

    const match = discovery?.matched_adapter

    return (
        <div className="blueprint-preview">
            {/* Adapter Discovery Result */}
            {discovery && (
                <div className={`discovery-banner ${discovery.path}`}>
                    {discovery.path === 'existing' && match ? (
                        <>
                            <span className="discovery-icon">🔗</span>
                            <span className="discovery-text">
                                <strong>Matched Adapter:</strong> {match.name} v{match.version}
                                <span className="confidence-badge">{(match.confidence * 100).toFixed(0)}%</span>
                            </span>
                            <span className="discovery-reason">{match.reason}</span>
                        </>
                    ) : (
                        <>
                            <span className="discovery-icon">🆕</span>
                            <span className="discovery-text">
                                <strong>New adapter profile</strong> — will be added to registry on deploy
                            </span>
                            {discovery.reason && (
                                <span className="discovery-reason">{discovery.reason}</span>
                            )}
                        </>
                    )}
                    {discovery.profiles_checked > 0 && (
                        <span className="discovery-checked">
                            Checked {discovery.profiles_checked} profile{discovery.profiles_checked !== 1 ? 's' : ''}
                        </span>
                    )}
                </div>
            )}

            {modelUsed && (
                <div className="model-badge">Generated by: {modelUsed}</div>
            )}

            <div className="preview-tabs">
                <button
                    className={`tab ${activeTab === 'blueprint' ? 'active' : ''}`}
                    onClick={() => setActiveTab('blueprint')}
                >
                    Blueprint Config
                </button>
                <button
                    className={`tab ${activeTab === 'catalog' ? 'active' : ''}`}
                    onClick={() => setActiveTab('catalog')}
                >
                    Catalog Entry
                </button>
            </div>

            <textarea
                className="json-editor"
                value={activeTab === 'blueprint' ? editableBlueprint : editableCatalog}
                onChange={(e) =>
                    activeTab === 'blueprint'
                        ? setEditableBlueprint(e.target.value)
                        : setEditableCatalog(e.target.value)
                }
                spellCheck={false}
                rows={18}
            />

            {jsonError && <div className="json-error">{jsonError}</div>}

            <div className="preview-actions">
                <button className="btn btn-secondary" onClick={onBack}>
                    ← Back to Input
                </button>
                <button
                    className="btn btn-simulate"
                    onClick={handleSimulate}
                    disabled={simulating}
                >
                    {simulating ? '⏳ Simulating...' : '▶ Simulate'}
                </button>
            </div>
        </div>
    )
}

export default BlueprintPreview
